version: "3.1"
services:
  web:
    image: odoo:15
    container_name: web-odoo
    depends_on:
      - db
    volumes:
      - odoo-mercdev-web-data:/var/lib/odoo-mercdev-web-data
      - ./config:/etc/odoo
      - ./local-addons:/mnt/extra-addons
    environment:
      - USER=odoo
      - PASSWORD=odoo
    networks:
      - odoo-mercdev
  db:
    image: postgres:13
    container_name: db-odoo
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-mercdev-db-data:/var/lib/postgresql/data/odoo-mercdev-db-data
    networks:
      - odoo-mercdev
  pgadmin:
    container_name: pgadmin-odoo
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: amdin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin-mercdev:/var/lib/pgadmin-mercdev
    ports:
      - 15433:80
    networks:
      - odoo-mercdev
    restart: unless-stopped
  proxy:
    container_name: proxy-odoo
    depends_on:
            - web
    container_name: odoo_proxy
    build:
        context: .
        dockerfile: Dockerfile-nginx
    ports:
        - "18069:8069"
    networks:
      - odoo-mercdev

networks:
  odoo:
    driver: bridge


volumes:
  odoo-mercdev-web-data:
  odoo-mercdev-db-data:
  pgadmin-mercdev:
